### ISSUE TITLE
Unable to build telegraf, yet circle ci says the last build of master succeeds?

### ISSUE THREAD

**Issue by ajohnstone** [influxdb/telegraf#93] opened 2015-08-06 09:26 UTC
Last build... https://circleci.com/gh/influxdb/telegraf/47
Not sure if I am missing something?

Using instructions from https://github.com/influxdb/telegraf/wiki/Building-from-source

```
andrew@andrew-laptop:~/Desktop/projects/github/ajohnstone/telegraf$ gvm install go1.4
Downloading Go source...
Installing go1.4...
 * Compiling...

andrew@andrew-laptop:~/Desktop/projects/github/ajohnstone/telegraf$ gvm use go1.4 --default
Now using version go1.4

andrew@andrew-laptop:~/Desktop/projects/github/ajohnstone/telegraf$ go get -u github.com/influxdb/telegraf/...

# github.com/influxdb/telegraf/plugins/kafka_consumer
/home/andrew/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/telegraf/plugins/kafka_consumer/kafka_consumer.go:76: cannot use k.Consumer.Messages() (type <-chan *"github.com/Shopify/sarama".ConsumerMessage) as type <-chan *"gopkg.in/Shopify/sarama.v1".ConsumerMessage in argument to readFromKafka
/home/andrew/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/telegraf/plugins/kafka_consumer/kafka_consumer.go:76: cannot use k.Consumer.CommitUpto (type func(*"github.com/Shopify/sarama".ConsumerMessage) error) as type ack in argument to readFromKafka

andrew@andrew-laptop:~/Desktop/projects/github/ajohnstone/telegraf$ cd $GOPATH/src/github.com/influxdb/telegraf

andrew@andrew-laptop:~/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/telegraf$ ./release.sh 
Building Telegraf version 0.9.b1
=> darwin-amd64: go build runtime: darwin/amd64 must be bootstrapped using make.bash
du: cannot access ‘pkg/telegraf-darwin-amd64’: No such file or directory
=> linux-amd64: # github.com/influxdb/telegraf/plugins/kafka_consumer
plugins/kafka_consumer/kafka_consumer.go:76: cannot use k.Consumer.Messages() (type <-chan *"github.com/Shopify/sarama".ConsumerMessage) as type <-chan *"gopkg.in/Shopify/sarama.v1".ConsumerMessage in argument to readFromKafka
plugins/kafka_consumer/kafka_consumer.go:76: cannot use k.Consumer.CommitUpto (type func(*"github.com/Shopify/sarama".ConsumerMessage) error) as type ack in argument to readFromKafka
du: cannot access ‘pkg/telegraf-linux-amd64’: No such file or directory
=> linux-386: go build runtime: linux/386 must be bootstrapped using make.bash
du: cannot access ‘pkg/telegraf-linux-386’: No such file or directory
=> linux-arm: go build runtime: linux/arm must be bootstrapped using make.bash
du: cannot access ‘pkg/telegraf-linux-arm’: No such file or directory

```

**Comment by sparrc** [comment] 2015-08-06 15:42
Thanks for the report, looking into it

**Comment by sparrc** [comment] 2015-08-06 15:45
@ajohnstone can you provide your OS?

**Comment by sparrc** [comment] 2015-08-06 16:24
confirmed that Ubuntu 14.04 is having this issue, I don't know why the circleci container doesn't capture that, will need to be investigated

**Comment by sparrc** [comment] 2015-08-06 19:07
this should be fixed, the problem appears to be with a gopkg.in package and it wasn't caught because of circleci build environment caching

**Closed by sparrc** 2015-08-06 19:07 UTC
Labels: bug

**Comment by ajohnstone** [comment] 2015-08-06 19:40
Great thanks :+1:
