### ISSUE TITLE
Telegraf 2.0 -> 2.2 breakage

### ISSUE THREAD

**Issue by mabushey** [influxdb/telegraf#390] opened 2015-11-23 19:04 UTC
I upgraded a server from 2.0 to 2.2.
```
Nov 23 18:56:55 www1 telegraf[19631]: 2015/11/23 18:56:55 ERROR: write failed: field type conflict: input field "value" on measurement "system_uptime" is type int64, already exists as type float
Nov 23 18:56:55 www1 telegraf[19631]: 2015/11/23 18:56:55 Error in output [influxdb-0]: Could not write to any InfluxDB server in cluster, retrying in 12.921399984s
```

How do I change "system_uptime" datatype to int64 from float?

**Comment by sparrc** [comment] 2015-11-23 19:13
This is likely due to this change: https://github.com/influxdb/telegraf/pull/372, I'll look into it

**Comment by sparrc** [comment] 2015-11-23 19:28
@mabushey I confirmed that gosigar was providing the uptime metric as `float64`, whereas gopsutil is providing it as a `uint64` (which we started using in Telegraf 0.2.1)

I actually think that gopsutil has it right, uptime _should_ be an int, but I'll convert it so as not to break backwards compatability.

**Comment by mabushey** [comment] 2015-11-23 19:30
Thanks for the lightning fast response! Sounds good. :) It will be nice to have FreeBSD compatibility too.

**Comment by sparrc** [comment] 2015-11-23 20:23
When I was working on a fix for this I realized that the gopsutil uptime implementation is pretty broken. We'll have to wait until this PR is merged to fix this: https://github.com/shirou/gopsutil/pull/114

**Comment by allen13** [comment] 2015-11-30 19:19
+1 on this issue. Also, shirou/gopsutil#114 was merged.

**Comment by sparrc** [comment] 2015-11-30 20:15
Unfortunately there is a Golang bug preventing me from updating the gopsutil dependency: https://github.com/golang/go/issues/11307

I'm going to wait until Go1.5.2 is released to get this out the door, since that should be any day now

**Comment by sparrc** [comment] 2015-12-04 20:50
@mabushey @allen13 Had to change some of the godep build process but I got gopsutil updated. This will be fixed in 0.2.4, thanks for your patience!

**Closed** 2015-12-04 20:55 UTC
Labels: bug

**Comment by allen13** [comment] 2015-12-04 21:25
Thanks!

**Comment by mabushey** [comment] 2015-12-04 21:50
Thank you for all you help @sparrc !

**Comment by Galser** [comment] 2015-12-11 10:10
And it is (problem) back for version 0.2.4.1 : 
2015/12/11 11:01:39 ERROR: write failed: field type conflict: input field "value" on measurement "system_uptime" is type float64, already exists as type integer

After upgrade from 0.2.3 to fresh 0.2.4.1. Should I create a new issue?

**Comment by pasancario** [comment] 2015-12-11 10:21
I'm facing the same problem with new 0.2.4.1 version: 

```
2015/12/10 17:27:20 ERROR: {"error":"write failed: field type conflict: input field \"value\" on measurement \"system_uptime\" is type float64, already exists as type integer"}
2015/12/10 17:27:20 Error in output [influxdb]: Could not write to any InfluxDB server in cluster, retrying in 10s
```

**Comment by Galser** [comment] 2015-12-11 10:23
Well, I already opened a new issue (I think it is a correct way to track changes), as it if specific to version upgrade between previous stable 0.2.3 and new 0.2.4, see it in the list, on top.
