### ISSUE TITLE
Language-agnostic Plugins

### ISSUE THREAD

**Issue by trehn** [influxdb/telegraf#24] opened 2015-06-23 09:04 UTC
Does Telegraf plan to allow users to write plugins in any language? Being able to quickly write something in Bash or Python would probably make a lot of ops people happy. Quite often I only need to collect a measurement once an hour or so, so the extra overhead would not be an issue at all.

Maybe this could be implemented as a plugin that just runs a configured list of commands with some configuration in env vars.

**Comment by atmaniak** [comment] 2015-06-23 10:06
It could also be nice to be able to specify a different duration between poll for each plugin.

**Comment by evanphx** [comment] 2015-06-24 21:25
@atmaniak you can do that already, check out Interval under https://github.com/influxdb/telegraf#plugin-options

**Comment by evanphx** [comment] 2015-06-24 21:26
@trehn It certainly could be implemented via an `exec` plugin that takes a list of programs to run. If they output JSON to stdout it should be easy enough to allow them to pass any number of values back as well.

**Comment by zepouet** [comment] 2015-07-09 16:59
Hello

@evanphx is it possible to use an unix socket to do communication between differents langages ?  I think it is a good way to have an universal plugin to gather metrics ?
The problem is for other environnement like windows... but for the moment I use it under MacOS and Linux.

If you like the idea, i could do a pull request about it. 

Best regards,
Nicolas

**Comment by sparrc** [comment] 2015-08-05 22:26
Sounds like a good idea, marking it as an enhancement request

**Comment by sparrc** [comment] 2015-08-06 19:31
see PR #92

**Closed by sparrc** 2015-08-06 19:31 UTC
Labels: enhancement
