### ISSUE TITLE
[0.1.4] disk_total now output as a float64, was previously output as an int64

### ISSUE THREAD

**Issue by beckettsean** [influxdb/telegraf#147] opened 2015-08-27 23:00 UTC
After upgrade to 0.9.3 and 0.1.4 on OS X I'm getting the following:

```
[http] 2015/08/27 15:58:20 127.0.0.1 - - [27/Aug/2015:15:58:20 -0700] POST /write?consistency=&db=telegraf&precision=&rp= HTTP/1.1 400 123 - InfluxDBClient 1c94a432-4d0f-11e5-8002-000000000000 1.202554ms
[write] 2015/08/27 15:58:31 write failed for shard 85 on node 1: field type conflict: input field "value" on measurement "disk_total" is type float64, already exists as type integer
```

It's entirely possible this is fixed in 0.1.6, but I can't get that via Homebrew yet.

**Comment by sparrc** [comment] 2015-08-28 15:46
InfluxDB 0.9.3 thinks that you're giving it a float64 because there is no `i` in the line protocol message to indicate an integer. marking this as a dupe of #146

**Closed by sparrc** 2015-08-28 15:46 UTC
