### ISSUE TITLE
Aggregate and Analyze Syslog

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#83] opened 2015-08-01 02:44 UTC
Is it possible to do with Telegraf what Fluentd does to aggregate and analyze Syslog with InfluxDB?

http://www.fluentd.org/guides/recipes/syslog-influxdb

**Comment by sparrc** [comment] 2015-08-05 22:36
+1, good idea for another plugin, adding as an 'enhancement'

**Comment by caquino** [comment] 2015-09-20 10:52
+1, this is useful for any kind of logs, for example mail logs.
It would be awesome to be able to specify logfiles and regexps for metrics extraction, with this it will be possible for example to collect metrics related to from/to deliveries on postfix.

IMHO being possible to specify one or more logfile to be parsed and one or more regexps to be matched on the logfile with named or positional matches that can be used for measurements and tags, will be very useful.

**Comment by steverweber** [comment] 2015-10-12 15:26
related: https://github.com/influxdb/telegraf/issues/83
perhaps have the logsreamer read from a network port instead of a file.

**Comment by sparrc** [comment] 2015-10-13 02:41
closing this as a duplicate of #102

**Closed by sparrc** 2015-10-13 02:41 UTC
Labels: enhancement, plugin request
