### ISSUE TITLE
telegraf\plugins\system\ps.go:70: cannot use du (type disk.DiskUsageStat) as type *disk.DiskUsageStat in append

### ISSUE THREAD

**Issue by tanderberg** [influxdb/telegraf#17] opened 2015-06-20 18:53 UTC
Tried to build Telegraf with go version go1.4.2 windows/amd64, got the error in the title,
telegraf\plugins\system\ps.go:70: cannot use du (type disk.DiskUsageStat) as type *disk.DiskUsageStat in append

**Comment by toddboom** [comment] 2015-06-20 19:09
@tanderberg awesome, thanks for the report - i assume there will be other Windows-specific issues, so keep reporting anything else you find

**Comment by discoduck2x** [comment] 2015-08-03 21:14
+1 , any solution or workaround?

**Comment by sparrc** [comment] 2015-08-05 22:24
@discoduck2x not yet, but marking this as a bug.

**Comment by sparrc** [comment] 2015-08-11 20:41
Closing because this is a duplicate of issue #30, Windows is not currently supported

**Closed by sparrc** 2015-08-11 20:41 UTC
Labels: bug, duplicate
