### ISSUE TITLE
kafka_consumer error in test-short

### ISSUE THREAD

**Issue by gotyaoi** [influxdb/telegraf#387] opened 2015-11-22 23:31 UTC
```
2015/11/22 15:15:04 Could not parse kafka message: cpu_load_short,host=server01 1422568543702900257, error: unable to parse 'cpu_load_short,host=server01 1422568543702900257': invalid field format
2015/11/22 15:15:04 Kafka Consumer buffer is full, dropping a point. You may want to increase the point_buffer setting
Measurement cpu_load_short, fields map[value:%!s(float64=23422)] not found
--- FAIL: TestRunParserAndGather (0.00s)
        Error Trace:    kafka_consumer_test.go:87
        Error:          Not equal: 0 (expected)
                                != 1 (actual)

        Error Trace:    kafka_consumer_test.go:88
        Error:          Should be true

FAIL
FAIL    github.com/influxdb/telegraf/plugins/kafka_consumer     0.018s
```
Got this when I ran the tests while compiling something unrelated in another terminal. Perhaps interestingly, the issue I mentioned in #385 did not show up on that test run.

**Comment by sparrc** [comment] 2015-11-23 17:45
I can't reproduce it, and unless it happens very frequently I'm going to mark it as "won't fix"

**Closed by sparrc** 2015-11-23 17:45 UTC

**Comment by gotyaoi** [comment] 2015-11-23 19:22
Ok, I'll reopen if I can manage to reproduce consistently.
