### ISSUE TITLE
Wrong format for InfluxDB 0.9.1?

### ISSUE THREAD

**Issue by pkkummermo** [influxdb/telegraf#41] opened 2015-07-03 08:36 UTC
I'm getting these in the log 

`[http] 2015/07/03 10:32:26 127.0.0.1 - - [03/Jul/2015:10:32:26 +0200] POST /write?consistency=&db=telegraf&precision=&rp= HTTP/1.1 400 106 - InfluxDBClient 08d797be-215e-11e5-8005-000000000000 2.541832ms`

When running telegraf_0.1.2_amd64 on Ubuntu Server 14.04 LTS

**Comment by dever860** [comment] 2015-07-03 15:07
Seconded. I am probably getting the same error you are. It looks like tags are still broken.

```
[root@CASS1 ~]# /opt/influxdb/telegraf -debug=true -config="/etc/opt/influxdb/telegraf.conf"
2015/07/03 15:05:27 InfluxDB Agent running
2015/07/03 15:05:27 Loaded plugins: cpu disk docker io mem memcached mysql net postgresql redis swap system
2015/07/03 15:05:27 Debug: enabled
2015/07/03 15:05:27 Agent Config: Interval:10s, Debug:true, Hostname:"blah.com"
2015/07/03 15:05:27 Sending metrics to: http://localhost:8086
2015/07/03 15:05:27 Tags enabled: dc=us-east-1 host=blah.com
> [cpu="cpu0"] cpu_user value=395.53
> [cpu="cpu0"] cpu_system value=309.21
> [cpu="cpu0"] cpu_idle value=1.00469253e+06
> [cpu="cpu0"] cpu_nice value=0.01
> [cpu="cpu0"] cpu_iowait value=3746.45
> [cpu="cpu0"] cpu_irq value=52.72
> [cpu="cpu0"] cpu_softirq value=93.02
> [cpu="cpu0"] cpu_steal value=0
> [cpu="cpu0"] cpu_guest value=0
> [cpu="cpu0"] cpu_guestNice value=0
> [cpu="cpu0"] cpu_stolen value=3.79
> [cpu="cpu1"] cpu_user value=280.57
> [cpu="cpu1"] cpu_system value=296.94
> [cpu="cpu1"] cpu_idle value=1.00779202e+06
> [cpu="cpu1"] cpu_nice value=0.02
> [cpu="cpu1"] cpu_iowait value=1159.98
> [cpu="cpu1"] cpu_irq value=0
> [cpu="cpu1"] cpu_softirq value=64.52
> [cpu="cpu1"] cpu_steal value=0
> [cpu="cpu1"] cpu_guest value=0
> [cpu="cpu1"] cpu_guestNice value=0
> [cpu="cpu1"] cpu_stolen value=0.45
> [] mem_total value=3924744000
> [] mem_available value=3738660000
> [] mem_used value=2144916000
> [] mem_used_prec value=4.7413028722382915
> [] mem_free value=1779828000
> [] mem_active value=1273228000
> [] mem_inactive value=710768000
> [] mem_buffers value=146572000
> [] mem_cached value=1812260000
> [] mem_wired value=0
> [] mem_shared value=0
> [interface="eth0"] net_bytes_sent value=39862464
> [interface="eth0"] net_bytes_recv value=347810986
> [interface="eth0"] net_packets_sent value=296707
> [interface="eth0"] net_packets_recv value=844890
> [interface="eth0"] net_err_in value=0
> [interface="eth0"] net_err_out value=0
> [interface="eth0"] net_drop_in value=0
> [interface="eth0"] net_drop_out value=0
> [] swap_total value=973074432
> [] swap_used value=0
> [] swap_free value=973074432
> [] swap_used_perc value=0
> [] swap_in value=0
> [] swap_out value=0
> [] system_load1 value=0
> [] system_load5 value=0
> [] system_load15 value=0
> [path="/"] disk_total value=40663146496
> [path="/"] disk_free value=38353330176
> [path="/"] disk_used value=2309816320
> [path="/"] disk_inodes_total value=2531328
> [path="/"] disk_inodes_free value=2503640
> [path="/"] disk_inodes_used value=27688
> [path="/proc"] disk_total value=0
> [path="/proc"] disk_free value=0
> [path="/proc"] disk_used value=0
> [path="/proc"] disk_inodes_total value=0
> [path="/proc"] disk_inodes_free value=0
> [path="/proc"] disk_inodes_used value=0
> [path="/sys"] disk_total value=0
> [path="/sys"] disk_free value=0
> [path="/sys"] disk_used value=0
> [path="/sys"] disk_inodes_total value=0
> [path="/sys"] disk_inodes_free value=0
> [path="/sys"] disk_inodes_used value=0
> [path="/dev/pts"] disk_total value=0
> [path="/dev/pts"] disk_free value=0
> [path="/dev/pts"] disk_used value=0
> [path="/dev/pts"] disk_inodes_total value=0
> [path="/dev/pts"] disk_inodes_free value=0
> [path="/dev/pts"] disk_inodes_used value=0
> [path="/dev/shm"] disk_total value=2009468928
> [path="/dev/shm"] disk_free value=2009468928
> [path="/dev/shm"] disk_used value=0
> [path="/dev/shm"] disk_inodes_total value=490593
> [path="/dev/shm"] disk_inodes_free value=490592
> [path="/dev/shm"] disk_inodes_used value=1
> [path="/boot"] disk_total value=499355648
> [path="/boot"] disk_free value=468709376
> [path="/boot"] disk_used value=30646272
> [path="/boot"] disk_inodes_total value=128016
> [path="/boot"] disk_inodes_free value=127977
> [path="/boot"] disk_inodes_used value=39
> [path="/proc/sys/fs/binfmt_misc"] disk_total value=0
> [path="/proc/sys/fs/binfmt_misc"] disk_free value=0
> [path="/proc/sys/fs/binfmt_misc"] disk_used value=0
> [path="/proc/sys/fs/binfmt_misc"] disk_inodes_total value=0
> [path="/proc/sys/fs/binfmt_misc"] disk_inodes_free value=0
> [path="/proc/sys/fs/binfmt_misc"] disk_inodes_used value=0
> [path="/var/lib/nfs/rpc_pipefs"] disk_total value=0
> [path="/var/lib/nfs/rpc_pipefs"] disk_free value=0
> [path="/var/lib/nfs/rpc_pipefs"] disk_used value=0
> [path="/var/lib/nfs/rpc_pipefs"] disk_inodes_total value=0
> [path="/var/lib/nfs/rpc_pipefs"] disk_inodes_free value=0
> [path="/var/lib/nfs/rpc_pipefs"] disk_inodes_used value=0
> [path="/vagrant"] disk_total value=51466960896
> [path="/vagrant"] disk_free value=42285989888
> [path="/vagrant"] disk_used value=9180971008
> [path="/vagrant"] disk_inodes_total value=3203072
> [path="/vagrant"] disk_inodes_free value=3192627
> [path="/vagrant"] disk_inodes_used value=10445
> [path="/share"] disk_total value=51466960896
> [path="/share"] disk_free value=42285989888
> [path="/share"] disk_used value=9180971008
> [path="/share"] disk_inodes_total value=3203072
> [path="/share"] disk_inodes_free value=3192627
> [path="/share"] disk_inodes_used value=10445
> [path="/share/files"] disk_total value=51466960896
> [path="/share/files"] disk_free value=42285989888
> [path="/share/files"] disk_used value=9180971008
> [path="/share/files"] disk_inodes_total value=3203072
> [path="/share/files"] disk_inodes_free value=3192627
> [path="/share/files"] disk_inodes_used value=10445
> [name="dm-0" serial=""] io_reads value=8794
> [name="dm-0" serial=""] io_writes value=6495949
> [name="dm-0" serial=""] io_read_bytes value=272618496
> [name="dm-0" serial=""] io_write_bytes value=25778126848
> [name="dm-0" serial=""] io_read_time value=4091
> [name="dm-0" serial=""] io_write_time value=70628568
> [name="dm-0" serial=""] io_io_time value=13163316
> [name="dm-1" serial=""] io_reads value=297
> [name="dm-1" serial=""] io_writes value=1
> [name="dm-1" serial=""] io_read_bytes value=1216512
> [name="dm-1" serial=""] io_write_bytes value=973074432
> [name="dm-1" serial=""] io_read_time value=58
> [name="dm-1" serial=""] io_write_time value=1
> [name="dm-1" serial=""] io_io_time value=59
> [name="sda" serial="QEMU_HARDDISK_QM00001"] io_reads value=7940
> [name="sda" serial="QEMU_HARDDISK_QM00001"] io_writes value=4343540
> [name="sda" serial="QEMU_HARDDISK_QM00001"] io_read_bytes value=286946304
> [name="sda" serial="QEMU_HARDDISK_QM00001"] io_write_bytes value=26751240192
> [name="sda" serial="QEMU_HARDDISK_QM00001"] io_read_time value=3426
> [name="sda" serial="QEMU_HARDDISK_QM00001"] io_write_time value=39786520
> [name="sda" serial="QEMU_HARDDISK_QM00001"] io_io_time value=13162885
> [name="sda1" serial="QEMU_HARDDISK_QM00001"] io_reads value=745
> [name="sda1" serial="QEMU_HARDDISK_QM00001"] io_writes value=13
> [name="sda1" serial="QEMU_HARDDISK_QM00001"] io_read_bytes value=12087296
> [name="sda1" serial="QEMU_HARDDISK_QM00001"] io_write_bytes value=38912
> [name="sda1" serial="QEMU_HARDDISK_QM00001"] io_read_time value=227
> [name="sda1" serial="QEMU_HARDDISK_QM00001"] io_write_time value=76
> [name="sda1" serial="QEMU_HARDDISK_QM00001"] io_io_time value=281
> [name="sda2" serial="QEMU_HARDDISK_QM00001"] io_reads value=7043
> [name="sda2" serial="QEMU_HARDDISK_QM00001"] io_writes value=4047574
> [name="sda2" serial="QEMU_HARDDISK_QM00001"] io_read_bytes value=274236416
> [name="sda2" serial="QEMU_HARDDISK_QM00001"] io_write_bytes value=26751201280
> [name="sda2" serial="QEMU_HARDDISK_QM00001"] io_read_time value=3138
> [name="sda2" serial="QEMU_HARDDISK_QM00001"] io_write_time value=28299569
> [name="sda2" serial="QEMU_HARDDISK_QM00001"] io_io_time value=1765567
2015/07/03 15:05:27 Error in plugins: unable to parse 'io_reads,dc=us-east-1,host=blah.com,name=dm-0,serial= value=8794': missing tag value
```

**Comment by jhofeditz** [comment] 2015-07-04 18:43
The error is caused by the missing serial tag value. Influxdb 0.9.1 now rejects writes with empty tag values as a 400 error.
Error in plugins: unable to parse 'io_reads,dc=us-east-1,host=blah.com,name=dm-0,serial= value=8794': missing tag value
I created PR influxdb/telegraf/pull/45 to fix this in the disk plugin.

To get the missing hostname tag, you also need to upgrade to telegraf-0.1.2

**Comment by sparrc** [comment] 2015-08-05 22:23
this was closed by PR 45, thanks!

**Closed by sparrc** 2015-08-05 22:23 UTC
